"""
Data models for the TsDefects pipeline using Pydantic for validation.

This module contains models that combine functionality from both defect_analysis
and pilger_processing pipelines while using TsSearch data models exclusively.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field, ConfigDict

# Import TsSearch models and IntentData
from vectordb_wrapper.ts_models import TsDefectResult
from gemba_agents.defect_analysis.models.data_models import IntentData


class TsDefectsConfig(BaseModel):
    """
    Configuration model for the TsDefects pipeline.
    
    This combines configuration from both defect analysis and pilger processing
    pipelines, adapted for TsSearch operations.
    """
    # Intent extraction configuration
    intent_agent_name: str = Field(
        default="jk_pilger_extract_intent_agent", 
        description="Name of the intent extraction agent"
    )
    
    # TsSearch configuration
    ts_search_base_url: Optional[str] = Field(
        default=None, 
        description="Base URL for TsSearch API. Uses HYBRID_SEARCH_BASE_URL env var if None"
    )
    search_limit: int = Field(
        default=10, 
        ge=1, 
        le=100, 
        description="Number of results to return from TsSearch"
    )
    min_similarity_score: Optional[float] = Field(
        default=0.2, 
        ge=0.0, 
        le=1.0, 
        description="Minimum similarity score for TsSearch results"
    )
    collection: str = Field(
        default="defects", 
        description="TsSearch collection to search in"
    )
    
    # Agent processing configuration
    processing_agent_name: str = Field(
        default="jk_pilger_defect_enhancement_curator_agent",
        description="Name of the agent for processing and enhancement"
    )
    config_path: str = Field(
        default="config/jk-gemba.yaml", 
        description="Path to agent configuration file"
    )
    
    # Pipeline configuration
    enable_logging: bool = Field(
        default=True, 
        description="Enable detailed logging"
    )
    enable_caching: bool = Field(
        default=True, 
        description="Enable result caching"
    )
    parallel_search: bool = Field(
        default=True, 
        description="Enable parallel vector searches"
    )
    timeout_seconds: int = Field(
        default=120, 
        ge=30, 
        le=300, 
        description="Timeout for agent processing in seconds"
    )

    model_config = ConfigDict(
        validate_assignment=True,
        extra="forbid"
    )


class EnhancedTsDefectResult(TsDefectResult):
    """
    TsDefectResult enhanced with agent processing fields.
    
    This extends the original TsDefectResult with additional fields
    generated by the agent processing stage.
    """
    curator_action: Optional[str] = Field(
        None, 
        description="Action recommended by the curator agent (e.g., REVIEW_REQUIRED, APPROVED, etc.)"
    )
    rationale: Optional[str] = Field(
        None, 
        description="Rationale or reasoning provided by the agent for the curator action"
    )

    model_config = ConfigDict(
        validate_assignment=True,
        extra="forbid"
    )


class TsDefectsResult(BaseModel):
    """
    Final result from the TsDefects pipeline.
    
    This contains the complete pipeline output including original input,
    extracted intent, and enhanced defect results.
    """
    original_input: str = Field(
        ..., 
        description="Original user input that was processed"
    )
    intent_data: IntentData = Field(
        ..., 
        description="Extracted intent data from the first stage"
    )
    total_results: int = Field(
        ..., 
        ge=0, 
        description="Total number of enhanced defect results"
    )
    enhanced_defects: List[EnhancedTsDefectResult] = Field(
        default_factory=list, 
        description="List of enhanced defect results with curator actions"
    )
    processing_time_ms: float = Field(
        ..., 
        ge=0, 
        description="Total processing time in milliseconds"
    )
    success: bool = Field(
        ..., 
        description="Whether the pipeline execution was successful"
    )
    error_message: Optional[str] = Field(
        default=None, 
        description="Error message if pipeline execution failed"
    )

    model_config = ConfigDict(
        validate_assignment=True,
        extra="forbid"
    )


class TsSearchResults(BaseModel):
    """
    Intermediate model for TsSearch results within the pipeline.
    
    This is used internally to pass search results between pipeline stages.
    """
    query_terms: List[str] = Field(
        ..., 
        description="Search terms used for the queries"
    )
    total_results: int = Field(
        ..., 
        ge=0, 
        description="Total number of results found"
    )
    execution_time_ms: float = Field(
        ..., 
        ge=0, 
        description="Total execution time for searches in milliseconds"
    )
    results: List[TsDefectResult] = Field(
        default_factory=list, 
        description="Raw TsDefectResult objects from search"
    )

    model_config = ConfigDict(
        validate_assignment=True,
        extra="forbid"
    )
