#!/usr/bin/env python3
"""
PepGenX OpenAI Wrapper - Setup Script

This script helps you set up the PepGenX OpenAI Wrapper quickly and easily.
It will guide you through the configuration process and verify everything works.

Usage:
    python setup.py
"""

import json
import os
import sys
import subprocess
from pathlib import Path


def print_header(title):
    """Print a formatted header."""
    print(f"\n{'='*60}")
    print(f"🚀 {title}")
    print(f"{'='*60}")


def print_step(step, title):
    """Print a formatted step."""
    print(f"\n📋 Step {step}: {title}")
    print("-" * 40)


def check_python_version():
    """Check if Python version is compatible."""
    if sys.version_info < (3, 8):
        print("❌ Python 3.8 or higher is required")
        print(f"   Current version: {sys.version}")
        return False
    print(f"✅ Python {sys.version.split()[0]} - Compatible")
    return True


def install_dependencies():
    """Install required dependencies."""
    print("Installing dependencies...")
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"])
        print("✅ Dependencies installed successfully")
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ Failed to install dependencies: {e}")
        return False


def create_env_file():
    """Create .env file with user input."""
    print("Creating .env configuration file...")
    
    # Check if .env already exists
    if os.path.exists(".env"):
        response = input("⚠️  .env file already exists. Overwrite? (y/N): ").lower()
        if response != 'y':
            print("✅ Using existing .env file")
            return True
    
    print("\n📝 Please provide your PepGenX configuration:")
    
    # Collect configuration
    config = {}
    
    config['PEPGENX_API_URL'] = input("PepGenX API URL: ").strip()
    if not config['PEPGENX_API_URL']:
        config['PEPGENX_API_URL'] = "https://test-api.pepgenx.com/generate"
        print(f"   Using default: {config['PEPGENX_API_URL']}")
    
    config['PEPGENX_PROJECT_ID'] = input("PepGenX Project ID: ").strip()
    if not config['PEPGENX_PROJECT_ID']:
        config['PEPGENX_PROJECT_ID'] = "test-project-123"
        print(f"   Using default: {config['PEPGENX_PROJECT_ID']}")
    
    config['PEPGENX_TEAM_ID'] = input("PepGenX Team ID: ").strip()
    if not config['PEPGENX_TEAM_ID']:
        config['PEPGENX_TEAM_ID'] = "test-team-456"
        print(f"   Using default: {config['PEPGENX_TEAM_ID']}")
    
    config['PEPGENX_API_KEY'] = input("PepGenX API Key: ").strip()
    if not config['PEPGENX_API_KEY']:
        config['PEPGENX_API_KEY'] = "test-api-key-789"
        print(f"   Using default: {config['PEPGENX_API_KEY']}")
    
    config['OKTA_TOKEN_FILE'] = input("OKTA Token File Path (default: okta_token.json): ").strip()
    if not config['OKTA_TOKEN_FILE']:
        config['OKTA_TOKEN_FILE'] = "okta_token.json"
    
    config['OPENAI_WRAPPER_API_KEYS'] = input("Wrapper API Keys (comma-separated, default: sk-test-key1,sk-test-key2): ").strip()
    if not config['OPENAI_WRAPPER_API_KEYS']:
        config['OPENAI_WRAPPER_API_KEYS'] = "sk-test-key1,sk-test-key2,sk-test-key3"

    # Optional settings
    print("\n📝 Optional settings (press Enter for defaults):")
    config['OPENAI_WRAPPER_HOST'] = input("Host (default: 127.0.0.1): ").strip() or "127.0.0.1"
    config['OPENAI_WRAPPER_PORT'] = input("Port (default: 8000): ").strip() or "8000"
    config['LOG_LEVEL'] = input("Log Level (default: INFO): ").strip() or "INFO"
    config['LOG_FORMAT'] = input("Log Format (default: json): ").strip() or "json"
    config['SECRET_KEY'] = input("Secret Key (default: auto-generated): ").strip() or "pepgenx-wrapper-secret-key-change-in-production-12345"
    
    # Write .env file
    try:
        with open(".env", "w") as f:
            f.write("# PepGenX OpenAI Wrapper Configuration\n")
            f.write("# Generated by setup.py\n\n")
            
            f.write("# PepGenX API Configuration\n")
            f.write(f"PEPGENX_API_URL={config['PEPGENX_API_URL']}\n")
            f.write(f"PEPGENX_PROJECT_ID={config['PEPGENX_PROJECT_ID']}\n")
            f.write(f"PEPGENX_TEAM_ID={config['PEPGENX_TEAM_ID']}\n")
            f.write(f"PEPGENX_API_KEY={config['PEPGENX_API_KEY']}\n\n")
            
            f.write("# OKTA Authentication\n")
            f.write(f"OKTA_TOKEN_FILE={config['OKTA_TOKEN_FILE']}\n\n")
            
            f.write("# Wrapper Configuration\n")
            f.write(f"OPENAI_WRAPPER_API_KEYS={config['OPENAI_WRAPPER_API_KEYS']}\n")
            f.write(f"OPENAI_WRAPPER_HOST={config['OPENAI_WRAPPER_HOST']}\n")
            f.write(f"OPENAI_WRAPPER_PORT={config['OPENAI_WRAPPER_PORT']}\n")
            f.write(f"LOG_LEVEL={config['LOG_LEVEL']}\n")
            f.write(f"LOG_FORMAT={config['LOG_FORMAT']}\n\n")

            f.write("# Security (required)\n")
            f.write(f"SECRET_KEY={config['SECRET_KEY']}\n\n")
            
            f.write("# Optional Settings\n")
            f.write("RATE_LIMIT_REQUESTS_PER_MINUTE=100\n")
            f.write("CORS_ORIGINS=*\n")
            f.write("ENABLE_METRICS=true\n")
        
        print("✅ .env file created successfully")
        return True
        
    except Exception as e:
        print(f"❌ Failed to create .env file: {e}")
        return False


def create_okta_token_file():
    """Create OKTA token file."""
    print("Creating OKTA token file...")
    
    # Get token file path from .env
    token_file = "okta_token.json"
    if os.path.exists(".env"):
        with open(".env", "r") as f:
            for line in f:
                if line.startswith("OKTA_TOKEN_FILE="):
                    token_file = line.split("=", 1)[1].strip()
                    break
    
    # Check if token file already exists
    if os.path.exists(token_file):
        response = input(f"⚠️  {token_file} already exists. Overwrite? (y/N): ").lower()
        if response != 'y':
            print(f"✅ Using existing {token_file}")
            return True
    
    print(f"\n📝 Creating {token_file}:")
    print("You can provide a real OKTA token or use the test token for development.")
    
    use_test = input("Use test token for development? (Y/n): ").lower()
    
    if use_test != 'n':
        # Create test token
        token_data = {
            "access_token": "test-okta-token-12345",
            "token_type": "Bearer",
            "expires_in": 3600,
            "scope": "test-scope"
        }
        print("   Using test OKTA token")
    else:
        # Get real token data
        token_data = {}
        token_data['access_token'] = input("OKTA Access Token: ").strip()
        token_data['token_type'] = input("Token Type (default: Bearer): ").strip() or "Bearer"
        
        expires_in = input("Expires In (seconds, default: 3600): ").strip()
        try:
            token_data['expires_in'] = int(expires_in) if expires_in else 3600
        except ValueError:
            token_data['expires_in'] = 3600
        
        token_data['scope'] = input("Scope (optional): ").strip()
        if not token_data['scope']:
            del token_data['scope']
    
    # Write token file
    try:
        with open(token_file, "w") as f:
            json.dump(token_data, f, indent=2)
        print(f"✅ {token_file} created successfully")
        return True
    except Exception as e:
        print(f"❌ Failed to create {token_file}: {e}")
        return False


def test_configuration():
    """Test the configuration by running a simple test."""
    print("Testing configuration...")
    
    try:
        # Try to import and validate configuration
        from app.core.config import settings
        print("✅ Configuration loaded successfully")
        
        # Check required settings
        if not settings.pepgenx_api_url:
            print("❌ PEPGENX_API_URL not configured")
            return False
        
        if not settings.api_keys_list:
            print("❌ OPENAI_WRAPPER_API_KEYS not configured")
            return False
        
        if not os.path.exists(settings.okta_token_file):
            print(f"❌ OKTA token file not found: {settings.okta_token_file}")
            return False
        
        print(f"✅ PepGenX API URL: {settings.pepgenx_api_url}")
        print(f"✅ API Keys configured: {len(settings.api_keys_list)}")
        print(f"✅ OKTA token file: {settings.okta_token_file}")
        
        return True
        
    except Exception as e:
        print(f"❌ Configuration test failed: {e}")
        return False


def main():
    """Main setup function."""
    print_header("PepGenX OpenAI Wrapper Setup")
    
    print("This script will help you set up the PepGenX OpenAI Wrapper.")
    print("It will guide you through configuration and verify everything works.")
    
    # Step 1: Check Python version
    print_step(1, "Check Python Version")
    if not check_python_version():
        return False
    
    # Step 2: Install dependencies
    print_step(2, "Install Dependencies")
    if not install_dependencies():
        return False
    
    # Step 3: Create .env file
    print_step(3, "Configure Environment")
    if not create_env_file():
        return False
    
    # Step 4: Create OKTA token file
    print_step(4, "Create OKTA Token File")
    if not create_okta_token_file():
        return False
    
    # Step 5: Test configuration
    print_step(5, "Test Configuration")
    if not test_configuration():
        return False
    
    # Success!
    print_header("Setup Complete!")
    print("🎉 PepGenX OpenAI Wrapper is ready to use!")
    print("\n📋 Next steps:")
    print("1. Start the server:")
    print("   python start.py")
    print("\n2. Test with a simple example:")
    print("   python examples/simple_usage.py")
    print("\n3. Check the documentation:")
    print("   - QUICK_START_GUIDE.md - 5-minute guide")
    print("   - USER_GUIDE.md - Complete manual")
    print("   - examples/ - Code examples")
    print("\n4. Test health endpoint:")
    print("   curl http://127.0.0.1:8000/health/")
    
    print(f"\n{'='*60}")
    print("🚀 Your PepGenX API is now OpenAI-compatible!")
    print(f"{'='*60}")
    
    return True


if __name__ == "__main__":
    try:
        success = main()
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Setup failed with error: {e}")
        sys.exit(1)
